### ISSUE TITLE
Decimal limits not working

### ISSUE THREAD

**Issue by mattster98** [andymchugh/andrewbmchugh-flow-panel#102]
I've tried both cellLabelDecimalPoints: 0 and decimalPoints: 0 but I'm still getting values displayed like below.

Not sure what I'm missing.  I tried with 2 (what I really want) but thought maybe zero would work.  Nothing has had an impact.

![image](https://github.com/user-attachments/assets/bc252c78-8d19-48d5-821f-ccbbff2db730)

**Comment by mattster98** [comment]
Seems to have been something related to the "units" not being a valid choice.  No YAML parsing error but I set it to "watt" and it seems to be happier now.

**Comment by andymchugh** [comment]
Thanks for pointing out. As you say, the decimal points are applied via the grafana units formatter so with invalid units it will not work. I've updated the yaml docs on main to highlight that the units must be valid.
