### ISSUE TITLE
How to properly export SVG files from diagrams.net (draw.io) so that they would be clickable

### ISSUE THREAD

**Issue by simonasmulevicius-humbility** [andymchugh/andrewbmchugh-flow-panel#103]
Hey, epic add-on! 

I was wondering, how do you export diagrams so that the users can interact with the diagram cells and click on the corresponding links? It seems that out-of-the-box example does work properly. 
However, it didnt work for me :,(.

![image](https://github.com/user-attachments/assets/dc1f5757-99df-40de-9277-fe11fa48008a)

I followed the following steps:
1. Copied your SVG: https://raw.githubusercontent.com/andymchugh/andrewbmchugh-flow-panel/main/examples/darkThemeSvg1.svg
2. I imported your SVG to diagrams.net without any changes
3. Exported using default parameters
4. Using simple localhost server I served myself the new SVG
5. When I put your and mine SVGs side by side, it seems that my diagram isn't clickable (Here I used the default Grafana Flow widget and just changed the SVG URL)
![image](https://github.com/user-attachments/assets/d6b2c633-3704-4ec3-a01b-e10d90a8586c)

Probably other community members would also benefit from knowing this.
Appreciate any guidance!

**Comment by andymchugh** [comment]
I think the online draw.io has recently changed so plugins defined on the url don't get loaded. You have to go to extras->plugins add svgdata. It's that plugin that preserves ids in the svg allowing it to map to the yaml. Can you give that a try?

**Comment by simonasmulevicius-humbility** [comment]
Oh, nice! That solved my problem! Thanks a lot

**Comment by simonasmulevicius-humbility** [comment]
Just final question - how do you keep the colors?
Because for me it seems that my imported-and-exported SVG has darker font colors:
![image](https://github.com/user-attachments/assets/70ee5ad7-0a6c-4a24-98c3-8ed55d51c8e1)

I am using the following settings for draw.io SVG export:
![image](https://github.com/user-attachments/assets/e7de7b0b-9786-4ba1-ab9c-23c085810009)

**Comment by andymchugh** [comment]
Great. I'll get the docs updated

**Comment by simonasmulevicius-humbility** [comment]
![image](https://github.com/user-attachments/assets/fff7e5d5-434e-4500-8363-4e8c67971451)
I've found an anwser to my previous question - it seems that classic theme should be used
