### ISSUE TITLE
Time slider defaults to time with no data for some values

### ISSUE THREAD

**Issue by mattster98** [andymchugh/andrewbmchugh-flow-panel#115]
This may be a Grafana bug, but I can't figure out how to work around it.  I have rolled up my high resolution data into 1 minute buckets for the Flow visualization.  Whenever I load the dashboard, it defaults to ~now() as the last and currently displayed time on the bottom time slider, but some of my fields have no values for that period because it's not :00 to align with my query min interval.

The two values that are always zero at the end are computed via transforms (just totaling two queries).  I would just blame it on the transform, but ALL of the displayed values are transforms used to rename the columns or do other math.  All my queries use mean() and fill(previous) so I don't think that's part of it.  My queries are also a mix of GUI queries on older data sources and FluxQL queries on newer ones, if that matters.

For example, the two values on the left going to the grid always show zero until I move the slider to the left at least one tick.

![image](https://github.com/user-attachments/assets/d0ae7e92-4031-4698-8c41-db00d8466469)

The data shows that I'm getting data for all the marks on the minute, but for the time the slider defaults to, it doesn't have all of them.

![Screenshot 2024-09-23 091012](https://github.com/user-attachments/assets/885f495a-c206-44dd-82ca-dc884455187d)

Like I said, maybe this is a Grafana thing I can fix (or even a bug there).  I've tried setting the time shift to see if that helps, but it does the same thing, just one minute in the past (still not on :00 seconds).

The two values that are always zero at the end are computed via transforms (just totaling two queries).  I would just blame it on the transform, but ALL of the displayed values are transforms used to rename the columns or do other math.  All my queries use mean() and fill(previous) so I don't think that's part of it.  My queries are also a mix of GUI queries on older data sources and FluxQL queries on newer ones, if that matters.

**Comment by andymchugh** [comment]
If the last value coming in is literally a zero I don't think there's anything the panel can do. It's a valid value to display. But above it looks like you may be getting null rather than zero. The datapoint chosen from the time-series defaults in the panel to last; but you can change that to lastNotNull. You can do that at the panel level or on individual widgets. The panel level setting is shown here: https://github.com/andymchugh/andrewbmchugh-flow-panel/blob/main/yaml_defs/panelConfig.yaml#L135

Does that help at all?

**Comment by mattster98** [comment]
Didn't seem to change anything.  I happened to refresh it when it was exactly on :00 and got a strange result..  The last timestamp appears twice - two rows - with values in those columns, and without.  This must be a grafana/query thing.  I also get weird results when I select shorter timeframes for the query..   Definitely nulls and zeros coming in then.  Not sure why that would be. I'll keep poking at the queries.

![image](https://github.com/user-attachments/assets/69f4aef2-df50-47e8-b283-3cb47d4a632d)

**Comment by andymchugh** [comment]
ok. To summarize, the timeSlider initial position is the last published time in the received data regardless of whether that data is used. If no data is received it sources the time window from the dashboard time window.

If you use datapoint='lastNotNull', then null values are walked back in time until a valid value (number or string) is found.

Under Debugging Data you can see exactly what the panel has received. A bit further upstream grafana has buttons to display what the query results actually are.

Given what you are showing in that picture, it's not showing zeros so I'd persevere a bit more in understanding what value is coming through. The panel shouldn't be converting a missing value to a zero. With 'last' it should show the label unmodified. with 'lastNotNull' it should walk back to a non null value.

**Comment by andymchugh** [comment]
Am going to close this out as the panel is correctly interpolating the data as far as I can tell. If the upstream transforms aren't behaving the way you expect with incomplete data then you could instead try the mathjs formulas in the bespoke drive. They would allow you to combine dataRefs exactly as you want.

**Comment by mattster98** [comment]
Sorry for the delay - finally getting back to this.  I think I understand the issue better, and it is Grafana, not Flow (but the lastNotNull seems like it should have helped but didn't)

Those two problematic fields are computed via "Total" transforms.  When the data is "null", Total outputs 0.  If I switch it to a math transform that just adds the two fields, when they are null, it outputs null.

In neither instance did the lastNotNull seem to help.  Is it supposed to walk back until ALL values are not null, or just one?  That wasn't clear to me.  Because, I can make it return null using the math, but I'm still seeing "NaN" on the visualization with lastNotNull in place.  It is just a top-level directive, right?  I only have it specified at the top level and not in any of the cells.  Here I have switched one from a Total transform to math addition.  You can see both NaN and zero displayed here with lastNotNull in place.

<img width="749" alt="image" src="https://github.com/user-attachments/assets/0a4b16af-d4a0-45ef-93bd-111a36796f1e">

Once I discovered what the Transform was doing I hunted for help there and found I could simply filter out null values using ANOTHER transform and now the slider is ending on :00 where there is data all around.

**Comment by andymchugh** [comment]
ok, thanks for the info. I'll reopen and check if lastNotNull is working correctly with the bespoke drive.

**Comment by andymchugh** [comment]
I double checked 'lastNotNull' on the bespoke drive and it appears to work fine for me. Maybe the disconnect is when it gets applied. The queries and transforms are all upstream of the panel plugin. It's only after that point that the panel gets presented with data. i.e. you have to have a null post transform for the lastNotNull to have any effect.
