### ISSUE TITLE
Mapping doesn't work with very long panelConfig.yml

### ISSUE THREAD

**Issue by JaakkoRautanen** [andymchugh/andrewbmchugh-flow-panel#118]
I'm using Flow plugin successfully. It works until my panelConfig.yml file (copy pasted into the panel) gets too long. For me it seems to be around 740 lines.

When debugging in Chrome it says:
`Loader.tsx:67 Error loading config. source = ---`
And then prints my complete yaml data.  Error also refers to `Loader.tsx`

If I comment one line out, it works.

yaml syntax has been verified. Any idea how to make it scale more?

**Comment by JaakkoRautanen** [comment]
Hmm.. I'm getting this error: `error = ReferenceError: Excessive alias count indicates a resource exhaustion attack`

**Comment by JaakkoRautanen** [comment]
Yes, it seems it is alias count which is limited. I can have 309 aliases in the yml. I can work around this by not using aliases, but my yaml gets wayyy longer.

**Comment by andymchugh** [comment]
Try splitting your setup between the siteConfig and the panelConfig. It tends to be layers of recursive aliases that blow the yaml-loader library recursion limit.

i.e. put your colors in siteConfig. It's having color -> threshold -> cell aliasing that really causes a problem on larger panels but just moving the colors out gives you lots more headroom. Have you tried that?

**Comment by andymchugh** [comment]
had a bit of a hunt and think the maxAliasCount is overidable, so will have a play and make it an option if it works out.

**Comment by andymchugh** [comment]
1.16.6 now published
