### ISSUE TITLE
localhost URL for svg file

### ISSUE THREAD

**Issue by tonio760** [andymchugh/andrewbmchugh-flow-panel#121]
hello
i tried to define local url for my svg file like this c:/myfolder/darkThemeSvg1.svg or with grafana folder "img" but that doesn't work

have you idea or suggestion ?

tanks for your answer

**Comment by andymchugh** [comment]
You'll need to use a global url or just paste the file content into the panel

**Comment by tonio760** [comment]
thanks
 so it's not possible also with this "file:///C:/myfolder/svg_test.svg" 
best regards

**Comment by andymchugh** [comment]
Yup. Not possible. You need to paste content or use an https url as per the examples

**Comment by tonio760** [comment]
thanks 
i have other mistake with svg file  when i open with drawio but i open a new issue
