### ISSUE TITLE
problem after modified svg file (darkThemeSvg1.svg) with drawio

### ISSUE THREAD

**Issue by tonio760** [andymchugh/andrewbmchugh-flow-panel#122]
hi
when i tried to modify svg file "darkThemeSvg1.svg" for my training with drawio v24.7.17
i had just deleted drawio icon and save the file 

but after paste content of new svg file , nothing works !!??
i compare the files and i see that ...

in your file we have  id="cell-inbox_depth"  and in the new file we have data-cell-id="inbox_depth"
so with instruction  cellIdPreamble: "cell-" that can't mapping 

if i replace the difference  in svg content id="inbox_depth" and change instruction in panel config  cellIdPreamble: ""  this work fine ....

i have you an idea for the reason ? maybe have you got solution ?

thanks 

best regards

**Comment by andymchugh** [comment]
It sounds like you haven't enabled the svgdata plugin in draw.io. can you confirm you have done that as per the getting started docs?

**Comment by tonio760** [comment]
i have enable plugin svgdata and that is ok but (sorry ) some background-color have been change (inbox_depth,active workers)

![image](https://github.com/user-attachments/assets/270f4c71-4c5f-4adb-8e74-3f5966b67094)

thanks for your help

**Comment by andymchugh** [comment]
I downloaded the same draw.io version, opened the svg in it, saved it as svg, pasted it into the panel. For me the backgrounds are still black. All I can suggest is to explore what your svg contains, try changing the settings in draw.io. Look at the svg in an svg beatifier such as https://codebeautify.org/svg-formatter-beautifier.  Format the svg in vscode so you can read it, reduce down to one widget so you have to read less. At some point what's happening for you should jump out and should be fixable with some draw.io setting.

This panel allows you to do a lot but that comes at some complexity. You have to put some time in exploring stuff.
