### ISSUE TITLE
how to add zabbix metrics in svg by using siteConfig.yaml?

### ISSUE THREAD

**Issue by yylime** [andymchugh/andrewbmchugh-flow-panel#126]
Hi, I am trying to read this  ![README](https://grafana.com/grafana/plugins/andrewbmchugh-flow-panel/)  to add a panel in Grafana, but I cannot find a way to add Zabbix metrics to the SVG. I wonder how to set the $dataRef$ parameter to make this work. Could you please give me some advice?

**Comment by andymchugh** [comment]
you add dataRef in panelConfig.yaml, not siteConfig. Just saying in case that's not a typo in the title. And the link you added is either private or broken, so not viewable.

First place to try would be following the getting started help: https://github.com/andymchugh/andrewbmchugh-flow-panel/tree/main/src#first-panel

**Comment by yylime** [comment]
> you add dataRef in panelConfig.yaml, not siteConfig. Just saying in case that's not a typo in the title. And the link you added is either private or broken, so not viewable.
> 
> First place to try would be following the getting started help: https://github.com/andymchugh/andrewbmchugh-flow-panel/tree/main/src#first-panel

Thank you so much, guys! I have found what was causing me trouble. I didn't close the $Test Data Generation$, and I think you might want to add this step in the documentation at [this link](https://github.com/andymchugh/andrewbmchugh-flow-panel/tree/main/src#first-panel), which I pasted above!"

**Comment by andymchugh** [comment]
great, I added a line to switch off test data generation, although it would only conflict if you were using the same dataRef names
