### ISSUE TITLE
panel slider on same line as highlight menu

### ISSUE THREAD

**Issue by bijwaard** [andymchugh/andrewbmchugh-flow-panel#15]
Hi Andy,
The new highlight menu is quite nice!

Could the time-slider be placed on the same line when there is horizontal space left, now it uses quite some vertical space in the panel.

Other panels like timeseries use the shared crosshair or tooltip (see dashboard options), could that be enabled for the flow as well such that the slider position synchronizes with the time-selection in other panels and vise-versa?
![image](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/6523124/c7a55215-f2b0-4167-b512-1ef4905dfe90)

Kind regards,
Dennis

![image](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/6523124/e16d0e3d-1e97-461a-9855-c9c65165ef14)

**Comment by andymchugh** [comment]
Yeah, the shared-cross hair would be nice. There's no plans to add it at the moment though. The initial aim with this was to ensure my panels had a future after Grafana 11.0. Maybe in the future. 

Re the side-by-side of the legend and timeSlider, don't think that's going to be worth it. Shorter timeSliders are quite hard to manipulate. The new scaling coming in 1.7 will give back a bit of screen real-estate and maybe on top of that I could add a *condensed* mode that removes the separator between the legend and the timeSlider. That gives back a quarter of the space and looks quite nice. Will think on it...

**Comment by andymchugh** [comment]
In version 1.7.0 there's a new file tagConfig.condensed. That reduces the vertical space used by 30%. The version also has better svg scaling so there's no wasted space in the svg part of the panel.

**Comment by bijwaard** [comment]
Great, "condensed:  true" under tagConfig indeed reclaims some virtual space for the diagram.

**Comment by andymchugh** [comment]
The shared-crosshair part of this ask has now also been done. It's available in 1.18.1. It's controlled with the new panel option 'Time Slider Mode'.

**Comment by bijwaard** [comment]
Thanks for implementing the shared-crosshair, this works very smoothly with the time-series panels!

**Comment by bijwaard** [comment]
One further remark after playing with the shared-crosshair and hover. When the time-slider is not visible, it is a bit strange that the diagram doesn't update when the Grafana timer occurs unless the last graph-point of a time-series was selected. It may be more natural that the diagram jumps to the updated Grafana time when the slider is not visible.

**Comment by andymchugh** [comment]
Thanks for the feedback. There's a lot tweaks that could be added but it gets complicated really fast.

At the moment the slider position isn't reset when the timeseries cross-hair is removed by a time-series panel. I chose this so people could mark a point and then move the mouse around the flow panel to point at things. Likewise the slider isn't reset when the time window updates or when a slider looses focus.

The main aim was to allow panel collaboration so at least one panel would have a slider and all collaborating panels would reflect its drive. To change behaviour in a panel based on whether any other panel has a collaborating slider visible or not would I think be too confusing.

So yes, at least one slider should be visible to have a cue as to what the display is showing.

**Comment by bijwaard** [comment]
I understand the complexity of finding out whether there is any other slider present. 

Another option could be to have a new slider mode in the panel besides "local", "time" and "position" that works similar to "time" and also follows the Grafana refreshes  (e.g. mode "refresh"). Then all flow panels that use this new mode would follow the Grafana refreshes, and flow panels with other modes would keep the last crosshair / slider position.
