### ISSUE TITLE
Custom units

### ISSUE THREAD

**Issue by bitlewis** [andymchugh/andrewbmchugh-flow-panel#16]
Greetings,

I'm trying to specify a custom unit in my panel configuration. The issue I have here is the unit I need is "ampere", however it converts them to kiloamperes when the value is above 1000.  With other plugins I am simply specifying a custom unit with the tag A and avoid the conversion.

Is there any way in the .yaml configuration to specify such custom units?

**Comment by bijwaard** [comment]
Those are quite heavy currents;-) I don't get near those values at home and LV substations, I'm using "amp" for units.
Maybe custom overrides could be enabled for the panel, can you show how you make such a custom unit in other panels?
Alternatively, the number of decimals could be utilized with a negative number to indicate the number of digits you want before the decimal.

**Comment by andymchugh** [comment]
> Greetings,
> 
> I'm trying to specify a custom unit in my panel configuration. The issue I have here is the unit I need is "ampere", however it converts them to kiloamperes when the value is above 1000. With other plugins I am simply specifying a custom unit with the tag A and avoid the conversion.
> 
> Is there any way in the .yaml configuration to specify such custom units?

Not at the moment. I could add a *units_postfix* field to the yaml that you could use alongside *number* maybe? I just had a look in a timeseries panel to see you they did it but couldn't see how you select a custom unit. Could you explain the steps?

**Comment by andymchugh** [comment]
I had a play & google and discovered if you type in the units field (as opposed to using the menus) you get the custom option in the normal grafana panels. I'm adding support for this in the plugins yaml with a new field *unitsPostfix*. There you can enter your custom units. It will get built into the next version.

**Comment by andymchugh** [comment]
This has been added now in version 1.7.0. Alongside *units* there's now a *unitsPostfix* field where you can add your custom unit.
