### ISSUE TITLE
Timeseries parsing issues when time column is not named 'time'

### ISSUE THREAD

**Issue by jammiemil** [andymchugh/andrewbmchugh-flow-panel#22]
Obligatory thanks for making this plugin! 

I and the people i work with have been having a great time using this plugin to replace flowcharting given the impending Angular-pocolypse

Weve been having a few small issues, one of which is that the 'time' column is [required ](https://github.com/andymchugh/andrewbmchugh-flow-panel/blob/main/src/components/TimeSeries.tsx#L63)to be named 'time' which is fine for 'most' datasources but some (such as Elasticsearch) use other field names (@timestamp being a common one) rendering the plugin unworkable.

Unfortunatly the transforms that work on field names only add a 'displayName' rather than changing the actual field name so this is near impossible to workaround.

For Example:

![image](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/54275278/430f1319-c96d-4881-a20c-57b18cfdfc7e)

![image](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/54275278/c6f68128-f5eb-4aaf-9a37-35f772f25f4b)

A few thoughts on how to fix this within the plugin:

- Allow the time field to be overriden in the panel config similar to dataRef/datapoint (Probably the best route?)
- Have the code [here ](https://github.com/andymchugh/andrewbmchugh-flow-panel/blob/main/src/components/TimeSeries.tsx#L63)updated to look in displaynames for 'time' also so that its possible to at least use transforms to get the plugin to work (A less great solution in my mind)
- Add a working mode that does not care about time and can accept basic table data (Appreciate this is a much larger ask but might be a good feature regardless)

**Comment by andymchugh** [comment]
Thanks for the feedback and screenshots. Nice to know you're finding the panel useful. I'll probably go the route of adding '@timestamp' of type=time as a 'time' name but making the set of names that can be time overridable via config. I think that sorts you out.

You mention other datasources use other names for time. Do you happen to know of any other datasource->timeName mappings?

**Comment by jammiemil** [comment]
Not off the top of my head but i will have a look through and see if i can spot any others with the datasources i use frequently. I should probably add that in Elastic @timestamp is the 'default' but actually the time field can be anything and there's no way to rename it as part of the query.

**Comment by andymchugh** [comment]
Thanks for the info. Don't worry about the other datasources. I'm going to change it to base the time series determination off of type which is the way the underlying grafana helpers do it.

**Comment by andymchugh** [comment]
The change for this is built into 1.8.0. I'll update here when it's got through the grafana review process.

**Comment by andymchugh** [comment]
The change for this in 1.8.0 is now available from Grafana.

https://grafana.com/grafana/plugins/andrewbmchugh-flow-panel/

Can you let me know if this is now ok for you?

**Comment by jammiemil** [comment]
Yes thats working for me now thank you!

Got a slightly different issue now but ill raise an issue if its something we cant work out.
