### ISSUE TITLE
value mapping fuction 

### ISSUE THREAD

**Issue by Victordr3** [andymchugh/andrewbmchugh-flow-panel#30]
Hello, I am using this panel to visualize my FCU (Fan Coil Unit) data. It is a powerful plugin.

I have the following data and I want to display the number as strings in SVG

0=low
1=middle
2=high 
3=auto

![image](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/168516545/bb0004c5-a70b-45ba-9c34-111fe72a801d)

Is it possible to include value mapping function similar to other Grafana panels in this panel?Thanks
![Screenshot 2024-04-30 144425](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/168516545/02e053a2-973a-4989-bf1b-444075f6347f)

**Comment by andymchugh** [comment]
thanks for trying the plugin. it does feel like something it should support. Will think it through...

**Comment by andymchugh** [comment]
This has been added in 1.11.0. Will ping when the release is published. Your data would need config as shown below under the cell.label space. There's an example in provisioning using yaml aliases in https://github.com/andymchugh/andrewbmchugh-flow-panel/blob/main/provisioning/dashboardData/dataMappings.yaml.
```
label:
  valueMappings:
    - {value: 0, text: "Low"}
    - {value: 1, text: "middle"}
    - {value: 2, text: "High"}
    - {value: 1, text: "auto"}
```

**Comment by andymchugh** [comment]
This has been published now if you want to give it a try. Reopen if you still have a problem
