### ISSUE TITLE
Time series with Length of 1 not rendering.

### ISSUE THREAD

**Issue by jammiemil** [andymchugh/andrewbmchugh-flow-panel#31]
Me Again!

Possibly abit of an edge case but unavoidable for the type of data we are working with.

The mapping of data to 'enriched' time series within the panel is reliant on there being more than 1 value in the returned dataset. If there is only a single value 'valuesIndex' gets set to Null rather than 0 and the data fails to render:

![image](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/54275278/efea7bf9-c499-47be-aaab-aafe5fa69bdb)

Working longer time series:

![image](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/54275278/aaed5337-4d53-4d39-b895-ead8ce73957e)

(Not actual Data im trying to use above but using it to create an example)

**Comment by andymchugh** [comment]
thanks for pointing out. will get that fixed.

**Comment by andymchugh** [comment]
Fix for this has been pushed to main and will get built into a release next week.

**Comment by andymchugh** [comment]
Great, thanks for confirming
