### ISSUE TITLE
Feature Request: Select which column to display in a label

### ISSUE THREAD

**Issue by jammiemil** [andymchugh/andrewbmchugh-flow-panel#37]
Sometimes datasets come back with more than just the Time and value columns, we have additional information in other columns that we might want to be able to put on our diagram via a label.

Currently you can only use the 'value'  field but it would be really useful to be able to choose which column in the dataset to use. For example:

![image](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/54275278/9909fae4-dab3-4cf2-9be3-eadbc8051bfa)

Rather than printing the value 1/0 on a component we might prefer to show the 'friendly_text' Success/Failure. Strictly speaking for this use case we could use valueMappings but the real use case i have in mind is much more complex than this.

'dataRef' lets us pick which time series to use and 'datapoint' lets us pick which row to use so were just missing a 'dataColumn'

**Comment by andymchugh** [comment]
That sounds interesting but I don't have any data sources available to me that can produce this data. Can you attach the expanded extract of the 'Debugging Data' log of a datasource that has this? Then I've got something explicit to code against. It's really tricky getting it right without that.

**Comment by jammiemil** [comment]
The above was made using the builtin [testdata](https://grafana.com/docs/grafana/latest/datasources/testdata/) datasource in 'csv content' mode

Data looked something like:

time,value,friendly_text
1715277266000,1,Success
1715277267000,0,Failure
1715277268000,1,Success

Heres the output of the debug (couldnt get a clean copy/paste of the text itself):

![image](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/54275278/e3ddf39c-9f1d-48ba-b4c1-70b62ee7ad8a)

**Comment by andymchugh** [comment]
thanks, so given above it looks like the data's there post enrichment, so am assuming its baulking on the type. prob just forces it to null when not a number. Will have a look.

**Comment by andymchugh** [comment]
built into ver 1.12.0 with grafana for review

**Comment by andymchugh** [comment]
Ver 1.12.0 now published on grafana
