### ISSUE TITLE
Feature request: Relative links

### ISSUE THREAD

**Issue by xkilian** [andymchugh/andrewbmchugh-flow-panel#39]
Relative links do not seem to be recognized, only full urls work. This is especially important for the URLS to be consistent regardless of the environment. Replicated dashboards across environments and for pre prod validation which do not use the same domain.

link: "/grafana/xyz/panel"

**Comment by andymchugh** [comment]
nice point. will get that added.

**Comment by andymchugh** [comment]
built into ver 1.12.0 with grafana for review

**Comment by andymchugh** [comment]
Ver 1.12.0 now published on grafana
