### ISSUE TITLE
Ability to set color for links

### ISSUE THREAD

**Issue by madansu** [andymchugh/andrewbmchugh-flow-panel#47]
Hi ! 
Thank you very much for starting this project ! Having our complex dashboard with myriad rules display in a clean manner is awesome. 
Does this panel have the ability to color links ? There are links that we want to show as Green or Red, depending on certain conditions, but as it stands today, our 1px wide links (arrows) only show the tips as colored. 

Here is a picture of what we have currently have from the flowchart visualization. 
<img width="1033" alt="Screenshot 2024-05-18 at 10 08 58 AM" src="https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/31675110/d8254a99-ef79-4f31-aab0-b1eb2927d8b0">

Is there any way to replicate this using the flow panel visualization ?

**Comment by andymchugh** [comment]
Thanks for the feedback. Good to know you're finding it useful. The short answer is no, the panel only offers up fill colors and I think we need stroke colors to make this feature work. I'll get that added, it looks like a nice extension.

**Comment by madansu** [comment]
Thank you ! That will be awesome.

**Comment by andymchugh** [comment]
This has now been landed and will be in the next build. strokeColor has the same look and feel as fillColor.

**Comment by andymchugh** [comment]
This is now published in version 1.13.0.

There's a demonstration [dashboard](https://github.com/andymchugh/andrewbmchugh-flow-panel/blob/main/provisioning/dashboards/strokeColor.json)

and corresponding [fillLevel svg yaml](https://github.com/andymchugh/andrewbmchugh-flow-panel/blob/main/provisioning/dashboardData/strokeColor_fillLevel.yaml)

and corresponding [flowAnim svg yaml](https://github.com/andymchugh/andrewbmchugh-flow-panel/blob/main/provisioning/dashboardData/strokeColor_flowAnim.yaml)
