### ISSUE TITLE
Feature Request: Variables and concatenation in Site and Panel config

### ISSUE THREAD

**Issue by micaelgg** [andymchugh/andrewbmchugh-flow-panel#49]
An example of use. Define a base URL in SiteConfig and be able to use it as a variable in Panel Config. Concatenating this variable with its own string for each cell.

It's just an idea. Your plugin is great :)

**Comment by xkilian** [comment]
We would also see a lot of value in a generic way to reference variables to build the URLs.
Ex. Add name of the metric in a cell or name of the cell as a variable to a URL.
This way If you have ten diffrent cells pointing to the same dashboard which accepts an input variable, we no longer need to define a unique URL for each cell. Something like $cell.name.

**Comment by andymchugh** [comment]
ok, will have a think.

**Comment by andymchugh** [comment]
I've added linkVariables to the siteConfig and panelConfig, so you can now do simple token substitution in link urls. This will be in the next build. I haven't added any special tokens though such as cell name as I'm assuming that can be the specific part.

Say if you have a usecase you think isn't supported by this.

[example use](https://github.com/andymchugh/andrewbmchugh-flow-panel/blob/main/provisioning/dashboardData/links.yaml#L78)

**Comment by andymchugh** [comment]
ok, have added ${cell.name} and ${cell.dataRef} as reserved tokens that will also be substituted in urls. That should improve it's usability.

Say if you think anything still remains in this issue.

**Comment by xkilian** [comment]
No, this should meet all my requirements.

**Comment by xkilian** [comment]
The only improvement would be on the usability side, support crtl-space, which opens a modal and shows the available variables, but I think that is a bit orthogonal this this here as it concerns more dasaboard variables and panel variables. Very useful when building data-links. I can open a different issue to discuss it and explore. I believe this issue can be closed. 
Thank you for all the hard work you have put in, we now have an real viable alternative(even better) to Flowcharting and Canvas.

**Comment by andymchugh** [comment]
published in version 1.14.0

**Comment by micaelgg** [comment]
Thank you so much <3
