### ISSUE TITLE
Add button to launch editing of SVG in draw.io diagrams.net and saving back to panel

### ISSUE THREAD

**Issue by xkilian** [andymchugh/andrewbmchugh-flow-panel#50]
Improve workflow by adding an _Edit diagram_ button that will launch diagrams.net with the json variable set and passing the svg data.
When saving, put the data back into the SVG code window.
This was supported in flowcharting, and was immensely useful editing existing panels.

**Comment by xkilian** [comment]
We have multiple environments that are not connected to our code repos, so having the options to directly edit in draw.io is very convenient. 
I understand there may be other SVG editors that people use, so the button may need to be named "Edit diagram in Draw.io" to avoid confusion

**Comment by andymchugh** [comment]
I don't think this will happen any time soon. My experience with those flowcharting buttons wasn't as positive as yours. I understand the lack of connectivity problem, but find with that the most enabling workflow to be having three UIs: draw.io desktop app + visual studio + the grafana. With a workflow of:
- edit the svg in draw.io app -> save but keep open
- copy paste svg from visual studio to panel
- edit yaml in visual studio
- copy paste yaml from visual studio to panel
With that workflow all UIs are kept open and don't have to re-initialise every time you want to tweak and try again. Plus the golden-source copy is held in your repo so it's easy to share with others.

I know this is opinionated, Everyone will gravitate to their own workflow. Just feel for now, this one is the one I want to promote.

**Comment by xkilian** [comment]
Not a problem, thank you for the answer.
