### ISSUE TITLE
URLs embedded in the SVG

### ISSUE THREAD

**Issue by xkilian** [andymchugh/andrewbmchugh-flow-panel#51]
Problem:
URL that were added to the draw.io SVG are recognized by the flow panel, the cursor changes to a pointing finger, but clicking does nothing.

Proposed Solution:
Improve documentation to indicate that urls in the SVG will not be honoured and MUST be defined in the site/panel config section.
or
Recognize and activate url links in the SVG. (FQDN or relative links)

**Comment by andymchugh** [comment]
will have a look.

**Comment by andymchugh** [comment]
I've tried this and it works for me on windows in google. So will close out unless you have some suggestions for why it's not working for you?

**Comment by xkilian** [comment]
I will give it another go and let you know.

**Comment by xkilian** [comment]
![image](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/1302719/877ae438-bd13-4991-b901-110b4dd513e4)

ZJ10 works and is associated with a URL tag in the panel config (This works)
ZJ14 is a data link that comes from draw.io (This does not work)

Next, I created a basic SVG with two boxes, same panel config, a link in the SVG for box ZJ14 (does not work) and a URL config for cell-ZJ10 (works).

Not quite sure what I am doing wrong.

`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="121px" height="151px" viewBox="-0.5 -0.5 121 151" content="&lt;mxfile host=&quot;Electron&quot; modified=&quot;2024-05-29T19:12:15.614Z&quot; agent=&quot;Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) draw.io/24.2.5 Chrome/120.0.6099.109 Electron/28.1.0 Safari/537.36&quot; etag=&quot;GYC-XjDiS8SswKp-6paZ&quot; version=&quot;24.2.5&quot; type=&quot;device&quot;&gt;&#10;  &lt;diagram name=&quot;Page-1&quot; id=&quot;uw7t4LPC0S-BInhWizU1&quot;&gt;&#10;    &lt;mxGraphModel dx=&quot;1842&quot; dy=&quot;1080&quot; grid=&quot;1&quot; gridSize=&quot;10&quot; guides=&quot;1&quot; tooltips=&quot;1&quot; connect=&quot;1&quot; arrows=&quot;1&quot; fold=&quot;1&quot; page=&quot;1&quot; pageScale=&quot;1&quot; pageWidth=&quot;1169&quot; pageHeight=&quot;827&quot; math=&quot;0&quot; shadow=&quot;0&quot;&gt;&#10;      &lt;root&gt;&#10;        &lt;mxCell id=&quot;0&quot; /&gt;&#10;        &lt;mxCell id=&quot;1&quot; parent=&quot;0&quot; /&gt;&#10;        &lt;UserObject label=&quot;ZJ14&quot; link=&quot;/grafana&quot; id=&quot;ZJ14&quot;&gt;&#10;          &lt;mxCell style=&quot;rounded=0;whiteSpace=wrap;html=1;&quot; vertex=&quot;1&quot; parent=&quot;1&quot;&gt;&#10;            &lt;mxGeometry x=&quot;200&quot; y=&quot;210&quot; width=&quot;120&quot; height=&quot;60&quot; as=&quot;geometry&quot; /&gt;&#10;          &lt;/mxCell&gt;&#10;        &lt;/UserObject&gt;&#10;        &lt;UserObject label=&quot;ZJ10&quot; id=&quot;ZJ10&quot;&gt;&#10;          &lt;mxCell style=&quot;rounded=0;whiteSpace=wrap;html=1;&quot; vertex=&quot;1&quot; parent=&quot;1&quot;&gt;&#10;            &lt;mxGeometry x=&quot;200&quot; y=&quot;120&quot; width=&quot;120&quot; height=&quot;60&quot; as=&quot;geometry&quot; /&gt;&#10;          &lt;/mxCell&gt;&#10;        &lt;/UserObject&gt;&#10;      &lt;/root&gt;&#10;    &lt;/mxGraphModel&gt;&#10;  &lt;/diagram&gt;&#10;&lt;/mxfile&gt;&#10;"><defs/><g><g id="cell-ZJ14" content="&lt;UserObject label=&quot;ZJ14&quot; link=&quot;/grafana&quot;/&gt;" data-label="ZJ14" data-link="/grafana"><a xlink:href="file:///grafana"><g><rect x="0" y="90" width="120" height="60" fill="rgb(24, 20, 29)" stroke="rgb(240, 240, 240)" pointer-events="all"/></g><g><g transform="translate(-0.5 -0.5)"><switch><foreignObject pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility" style="overflow: visible; text-align: left;"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 118px; height: 1px; padding-top: 120px; margin-left: 1px;"><div data-drawio-colors="color: rgb(240, 240, 240); " style="box-sizing: border-box; font-size: 0px; text-align: center;"><div style="display: inline-block; font-size: 12px; font-family: Helvetica; color: rgb(240, 240, 240); line-height: 1.2; pointer-events: all; white-space: normal; overflow-wrap: normal;">ZJ14</div></div></div></foreignObject><text x="60" y="124" fill="rgb(240, 240, 240)" font-family="Helvetica" font-size="12px" text-anchor="middle">ZJ14</text></switch></g></g></a></g><g id="cell-ZJ10" content="&lt;UserObject label=&quot;ZJ10&quot;/&gt;" data-label="ZJ10"><g><rect x="0" y="0" width="120" height="60" fill="rgb(24, 20, 29)" stroke="rgb(240, 240, 240)" pointer-events="all"/></g><g><g transform="translate(-0.5 -0.5)"><switch><foreignObject pointer-events="none" width="100%" height="100%" requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility" style="overflow: visible; text-align: left;"><div xmlns="http://www.w3.org/1999/xhtml" style="display: flex; align-items: unsafe center; justify-content: unsafe center; width: 118px; height: 1px; padding-top: 30px; margin-left: 1px;"><div data-drawio-colors="color: rgb(240, 240, 240); " style="box-sizing: border-box; font-size: 0px; text-align: center;"><div style="display: inline-block; font-size: 12px; font-family: Helvetica; color: rgb(240, 240, 240); line-height: 1.2; pointer-events: all; white-space: normal; overflow-wrap: normal;">ZJ10</div></div></div></foreignObject><text x="60" y="34" fill="rgb(240, 240, 240)" font-family="Helvetica" font-size="12px" text-anchor="middle">ZJ10</text></switch></g></g></g></g><switch><g requiredFeatures="http://www.w3.org/TR/SVG11/feature#Extensibility"/><a transform="translate(0,-5)" xlink:href="https://www.drawio.com/doc/faq/svg-export-text-problems" target="_blank"><text text-anchor="middle" font-size="10px" x="50%" y="100%">Text is not SVG - cannot display</text></a></switch></svg>`

**Comment by andymchugh** [comment]
Thanks for the svg. Links maintained in the yaml are known about and when clicked get passed through variable substitution and relative-logic to create valid absolute urls that then get opened.

links defined in the svg are opaque to the panel. They go through the panel click handler, aren't recognised and then get handled by the underlying react framework. So you get none of the extra bits.

That means absolute links work but with no variable substitution and relative links (as in your example) just get ignored.

Reckon links that you want the panel to manipulate need to be in the yaml. Links in the svg are just pass through and you get what you get. I'll make the yaml docs clear on this. Thanks for pointing out

**Comment by xkilian** [comment]
Thank you for the explanation, I will redefine my urls the yaml.
Updating the docs will make it clear.
Your work is very much appreciated.

**Comment by andymchugh** [comment]
Thanks. have updated the docs
