### ISSUE TITLE
Migrating from algenty flow charting plugin

### ISSUE THREAD

**Issue by yanisbinks** [andymchugh/andrewbmchugh-flow-panel#52]
Hello,

I am trying to migrate my dashboard from algenty's plugin to this new one.

I opened one of my pannels on draw.io, activated the SVG plugin and exported my pannel to an SVG file. I then copied the code of the SVG into my new grafana dashboard.

The problem is that i can't manage to make him as big and readable as it was. 

I can play around with the zoom and margins options but this doesnt really do the trick. 

My pannel shows up so tiny that i can't even read it.

Do you guys have any tips on migrating ? 

Thank you for your answers

**Comment by andymchugh** [comment]
All the scaling problems on larger svgs were believed to be solved in version 1.7. Do you know what version of the plugin you are on? If not sure the ability to zoom/pan in the panel was added in 1.9 so say if you have that functionality.

If you are in an earlier version just upgrade. If on the latest, attach your svg here and I can have a look at it

**Comment by yanisbinks** [comment]
Hello
Thanks a lot for your answer. I updated the plugin and i can now zoom in.
