### ISSUE TITLE
Enable Plugin Functionality Without a Time Column

### ISSUE THREAD

**Issue by newita1** [andymchugh/andrewbmchugh-flow-panel#54]
Is it possible work with this plugin without a timestamp column? I have to map the current status and i only recibe the value without timestamp column. Please, You can help me?

**Comment by andymchugh** [comment]
could you press 'Debugging Data' and attach here the raw and enriched data that gets logged in the console? That way I'll get a better understanding of the data form you have.

**Comment by andymchugh** [comment]
without an example input there's no easy way to progress this so closing out.
