### ISSUE TITLE
Add link in grafana.com plugins to point back to github repo

### ISSUE THREAD

**Issue by xkilian** [andymchugh/andrewbmchugh-flow-panel#6]
First off, congratulations on a great idea and interesting implementation. I look forwarding to testing it.

Please add link in grafana.com plugins to point back to the github repo.

**Comment by andymchugh** [comment]
Thanks for the feedback. There is a link at the bottom of https://grafana.com/grafana/plugins/andrewbmchugh-flow-panel/ under 'Want to Make Changes', but the name of 'Grafana Getting Started' is a bit confusing. I'll add a more obvious link back in the next release and close out the issue when the version is pushed.

**Comment by xkilian** [comment]
I usually look for the link back to the github repo on the sidebar: Ressources and Projet Site. Just under Developer.

**Comment by andymchugh** [comment]
> I usually look for the link back to the github repo on the sidebar: Ressources and Projet Site. Just under Developer.

thanks, I'll get that added

**Comment by andymchugh** [comment]
Links now added as 1.6.0. https://grafana.com/grafana/plugins/andrewbmchugh-flow-panel/

Thanks for the tip.
