### ISSUE TITLE
Feature Request: Insert value or value-mapping to a cell

### ISSUE THREAD

**Issue by xkilian** [andymchugh/andrewbmchugh-flow-panel#66]
A cell may represent an object like a square. When assigning the label attribute to a geometric cell. 
Insert the value into the object.

Say for example a metric represents the number of alerts. This number could appear in the square, without having pre-defined a text object in the square.
![image](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/1302719/ebe35cf7-7762-4086-ac78-9106caeaef1f)

**Comment by andymchugh** [comment]
I'll have an explore. My gut reaction is the inner text element is a place where location and font and other settings should be defined so it makes sense for it to be predefined in the svg. But that could just be misguided so I'll delve into it.

**Comment by andymchugh** [comment]
I had a look at this and have decided not to do it. I accept it would be better with it but I don't want to go down the path where I'm building out the svg structure. That's what draw.io excels at. When you look at a rect with no label, and one with a label, the structure around the two is quite different. By adding the label you get to see the thing you want adjusting, position it, play with the font, etc. You have a starting point for troubleshooting it. So sorry, but decided for now this is out of scope.
