### ISSUE TITLE
feature request: measurement-based dynamics

### ISSUE THREAD

**Issue by bijwaard** [andymchugh/andrewbmchugh-flow-panel#67]
Hi Andy,

The flow panel gets more complete every time I update, great work!

It would be nice to be able to add dynamics to the flow from measurements similar to what the marcuscalidus-svg-panel does. To integrate this functionality, I can imagine the following updates to flow panel, hopefully keeping effort on the flow panel side minimal while adding much animation freedom for the users:

- In YAML users would specify which SVG element shapes would change based on which measurements.
- The user can write a javascript function that receives the SVG ID, and an array of or more measurements as parameters, this function can  dynamically change the shape based on these measurements.
- The javascript function would be triggered at every Grafana refresh and/or when the time-slider changes.
- Being able to also add some javascript initialisation variables and functions would also be great, e.g. with MouseClick and MouseWheel callbacks for animation based on mouse wheel or click.

Kind regards,
Dennis

**Comment by bijwaard** [comment]
Some further remarks:

- Probably better that the call-back function receives the actual SVG element instead of the ID, else it would need the active SVG document to look up the ID. The function would take care of checking graphical boundaries for x,y positions.
- mouse events would be less important, but could potentially make the flow even more interactive

The dynamic SVG that I was thinking of are:
- gauges, dials
- embed the phasors that I now use with the (deprecated) SVG plugin into a flow diagram 
![image](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/6523124/6ce2f3cf-d1b6-4a61-8987-34cc5c2e2399)

- and anything other users can think of;-)

**Comment by allomorphy** [comment]
Amazing @andymchugh if this could be feasible for you and thanks to @bijwaard for that suggestion.

Our first use case involves a version of a gauge like the standard Grafane gauge but it needs to embed on a seelected graphical background. Would love to do that with the amazing flow-panel.

All for this brave new world of dynamic widgets in flow-panel
👏 

E

**Comment by andymchugh** [comment]
Can you give a few concrete examples of what you want to drive? i.e. in your phasor do each of the colored lines have unique ids? do you want to change their full 'path' attribute based on a single data reference, what is your algorithm for going from data to cell attributes, etc. With concrete examples of your data input, your svg and how you would change your cell attriutes I can have a think what would work with the general panel concepts. It's much harder to take an abstract ask because by the time it's translated into something functional it might no longer do the thing you really needed.

**Comment by bijwaard** [comment]
Hi Andy,

Sorry for the abstract description, but I was unsure if my specific use case could be generalized from a YAML description alone, that is why I thought of Javascript functions for panel-user, inspired by my usage of the SVG plugin.

Concretely, in my use-case I want to drive the end-point of a line (phasor) from 2 measurements. The input consists of two values, say x and y, that would drive the end-point of the arrow. My SVG for the first phasor line L1 looks as follows:

```
<marker id="markerArrowRed" markerWidth="3" markerHeight="3" refX="1.5" refY="1.5" orient="auto">
          <path d="M1,0 L1,3 L2,1.5 L1,0" style="fill: red" />
</marker>
<line id="L1" x1="100" y1="100" x2="100" y2="45" style="stroke-width: 3px; stroke: red; marker-end: url(#markerArrowRed);"
```
Essentially, I would like to drive the x2 and y2 of the L1 line endpoint from the measurements x and y. Since the measurement values can have a wide range, the magnitude sqrt(x^2+y^2) may need to be scaled down to a certain zoom-level to be within range of the circles in the diagram. The same goes for other phasors like L2, L3 (and Neutral for current). The phasors can be either for current, voltage or power.

In my original SVG panel I used javascript to change the zoom-level using the middle-mouse actions up/down while hoovering above the diagram and adjust the numbers on the circles, and a click on the area to fix the zoom-level to the maximum for all phasors in the same plot. Auto-scaling the magnitude could also be an option in most cases, but they may give false interpretation when comparing phasor plots of the same type (e.g. voltage).

The other use-case from @allomorphy with a gauge, would just drive the end-point of the line on the rim of a circle/ellipse, this would also change x2 and y2 in a more proportional way from one measurement to stay on the circle/ellipse boundary.

Kind regards,
Dennis

**Comment by andymchugh** [comment]
great, thanks for info. will have a think...

**Comment by andymchugh** [comment]
Just a heads up, work on this is in progress in the form of a general purpose attribute drive where your javascript (defined in the yaml) receives data+grafanaVariables+svgElementCopy and you get to return attributes to be added to the svgElement.

If you need to drive more than just svg-element-attributes do say. I think this meets the usecase described above...

**Comment by bijwaard** [comment]
Hi Andy,
Thanks for the heads up and support!  A callback function definition in the yaml file sounds great.

At the moment only svg-element attributes (x2 and y2 of the phasor lines) and text labels (the magnitude label such as 5 below the circles) would be driven by measurements.

```
<line id="L1" x1="100" y1="100" x2="100" y2="45" style="stroke-width: 3px; stroke: red; marker-end: url(#markerArrowRed);"
<text id="label100" x="100" y="200" fill="black" text-anchor="middle" style="text-anchor: middle; dominant-baseline: middle;">5</text>

```
Some questions:
- I guess yaml supports multi-line to keep the javascript function kind-of readable, or can you alternatively specify a html reference to the javascript function which may make it easier to edit&maintain?
- Can the javascript function get the data of multiple measurements, e.g. both x and y value of a phasor line?
- Could the javascript function drive more than one SVG element, e.g. when magnitude of all phasors gets too high/low, we want to change all circle labels
- Can the remembered values like "last maximum magnitude" be used in other javascript functions? E.g. each phasor line callback function would update the maximum magnitude, and the circle label(s) callback updates the label text according to the maximum magnitude used to scale the phasor lines.
- Would there be a predefined sequence in which the javascript callbacks will be called? I.e. the new magnitude for changing the circle labels would only be known when all three phasor line callbacks have been called
- Can additional arguments be given to the javascript function, e.g. the circles need to know their fixed fraction of the maximum magnitude, or can it better be defined in the SVG element (like fraction="0.2" for id="label20" below) and accessed from the element within the javascript callback function?
`<text id="label20" x="100" y="120" fraction="0.2" fill="black" text-anchor="middle" style="text-anchor: middle; dominant-baseline: middle;">1</text>`

Btw. We may be able to calculate the maximum magnitude in the current grafana refresh and only use it in the next grafana refresh to update the circle labels and scale the phasor lines accordingly. In that case sequence of callbacks probably does not matter much.

Kind regards,
Dennis

**Comment by andymchugh** [comment]
yaml multi-line: yes

multiple dataRefs: yes

multiple elements: no. Don't yet understand why you'd need that. If there's some shared scalar i'd have thought that's one line of javascript you'd have in the function. Say if its more complex than that?

remembered values: yes within the function. There'll be a state object that can be built up. Not planned across functions but open if there's a compelling argument.

label text: not planned as part of this as text tends not to be in attributes. Can you explain a bit more why you need a bespoke text drive?

predefined sequence: kindof in that the svg is traversed depth first but I wouldn't expect you to rely on it as it sounds very brittle. It has some meaning for things like double arrowed connectors where the three path elements are ordered body-leftArrow-rightArrow.

additional args: I guess you are thinking about a shared javascript function and those args being like 'template specialisation'. That could be added. Is this the usecase you are thinking of?

**Comment by andymchugh** [comment]
I've looked again at your circle legends and I think understand your need for bespoke label text too. Will think on how to incorporate it

**Comment by bijwaard** [comment]
**multiple elements:** Driving multiple elements from one function is not crucial, when we can easily re-use the same function on multiple SVG elements, e.g. with a given argument.

**Remembered values:** when we cannot remember state across functions, we may will probably create one function that drives functionality for different things based on a given argument.

**Label text:** 

The text fields would be used for showing magnitude scale of the phasor lines, e.g. when the phasor denotes power and you often don't know beforehand what the range of amount will be, can be 100W, 1kW, 10kW or even a few 100kW on a substation. With autoscaling you could automatically apply a scaling factor depending on the current value range and more easily see the line differences:
- a smaller scaling factor would translate in shorter phasor lines and higher magnitude labels on the circles
![image](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/6523124/b19c896c-273e-4a60-a774-ad794e391e3a)
- a higher scaling factor would translate in larger phasor lines and smaller magnitude labels on the circles
![image](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/6523124/6e1ff26b-4f00-4f0f-8967-f30aa4eb4a6f)
- yes, additional arguments would make it easier to create more generic javascript functions, e.g. one function for all three phasor lines, and one function for all circle labels. Or one combined function that drives both phasor line and circle labels and shares some state.

An alternative to autoscaling by remembering magnitude could be to set a maximum magnitude from a grafana template variable and display that value on the outer circle of the phasor plot and add it as a callback function argument. That would mean driving the label value from a template variable. This template variable would then also be an additional argument for the callback functions.

**predetermined sequence**: agree that relying on this sequence is asking for trouble later

**additional args:** depending on the options above 1 or two additional arguments for the callback functions would be help:
- 1 argument to distinguish element behavior and make function more generally applicable
- 1 argument to pass a value or template variable (e.g. to be used as maximum magnitude for scaling the lines)

**Comment by andymchugh** [comment]
Great. That makes sense. Thanks for info.

**Comment by andymchugh** [comment]
Although a version that supports this is ready, it's not looking publishable as the use of client defined javascript would mean the panel being marked as high risk. So am thinking through alternatives...

**Comment by xkilian** [comment]
Yeah, this is an issue for us. We have chosen not to use plugins that permit client side javascript. If there is an alternative that would be best, or a way to disable the feature should someone not require it.

**Comment by bijwaard** [comment]
Sorry to hear that client-side javascript is discouraged within the plugin. Instead of specifing the javascript in the panel or JAML, we could embed the javascript function(s) in the SVG diagram and invoke it from a YAML definition. Would that be better a better option? Else we may end up creating a new language/specification to do get the same functionality & flexibility.

**Comment by andymchugh** [comment]
yeah, all javascript gets cleaned out of the svg before presentation, that was a pre-requisite for the other versions being published. I'm prob going to use mathjs as an alternative. javascript and on/off switches are off the table now as I do need this plugin to be unflagged. Think controlling things like your phasor will still be very viable though.

**Comment by bijwaard** [comment]
Indeed mainly a bunch of math expressions would be needed for the phasor lines, I hope mathjs would allow updating a number of svg attributes and keep some state. Hope changing the label tags for scaling would also be possible.

**Comment by andymchugh** [comment]
yup, that remains the goal.

**Comment by bijwaard** [comment]
Just checked mathjs a bit, you can probably use the measurements and other parameters as input scope and have the a sequence of expressions return name-value pairs via the updated scope for the named attributes and/or tag, e.g.:
```
const scope = { a:5, b: 10 };
const expressions = [
'c = a + b',
'd = c * 2'
];

math.evaluate(expressions, scope);

const results = {
c: scope.c,
d: scope.d
};
```

**Comment by andymchugh** [comment]
Version 1.16.1 got published today that I believe will meet this need. With it you get the ability to extract svg-element-attribute values, combine data-series with these values in mathjs formulas, then drive attribute values off of these derived terms. You aren't going to get any 'on*' attribute drivability but I think everything at the heart of what you want is doable. The example below shows lines rotating, and range-rings scaling with co-located labels being driven from these derived terms.

https://raw.githubusercontent.com/andymchugh/andrewbmchugh-flow-panel/ver_1.16.1/examples/darkThemeSvg5.svg
https://raw.githubusercontent.com/andymchugh/andrewbmchugh-flow-panel/ver_1.16.1/examples/panelConfig5.yaml

Can you have a play and say if there's still some feature missing that's needed? Keep in mind any attribute value containing javascript is just going to be a 'no'. It won't get through review.

**Comment by bijwaard** [comment]
Thanks Andy, I will play with your update as soon as I can (currently on family vacation in Spain). From the updated YAML I see you've made quite some changes to give flexibility for the users.

**Comment by andymchugh** [comment]
no worries. no rush. Have a nice holiday :)

**Comment by andymchugh** [comment]
going to close this out now. If you have problems, feel free to reopen it.

**Comment by bijwaard** [comment]
Hi Andrew,

I'm playing with the dynamics, your panelConfig5.yaml demo looks great.

However, I have a problem getting attribute "r" from my SVG circle, maybe because my circles are not enclosed in a SVG group:

```
    <defs>
      <marker id="markerArrowRed" markerWidth="3" markerHeight="3" refX="1.5" refY="1.5" orient="auto">
          <path d="M1,0 L1,3 L2,1.5 L1,0" style="fill: red" />
      </marker>
    </defs>
    <circle id="circle100" style="stroke: black; fill: lightgrey; fill-opacity:0.5" cx="100" cy="100" r="100"/>
    <text id="label100" x="100" y="200" fill="black" text-anchor="middle" style="text-anchor: middle; dominant-baseline: middle;">5</text>
     <g>
      <line x1="100" y1="100" x2="100" y2="45" style="stroke-width: 3px; stroke: red; marker-end: url(#markerArrowRed);"       id="L1" />
     </g>
``` 

Driving the line works when maxRadius is used as formula, but not when I try to obtain it from the circle100 attribute "r".

```
  circle100:
    bespoke:
      namespace: "clock"
      formulas:
      - "maxPower=10000"
      #- "maxRadius=100"
      - "utils.log('log circle100 maxPower=',maxPower)"
      drives:
        # capture max radius of circle to drive arrow
        - elementName: "circle100"
          attribsGet:
            maxRadius: "r"
        #- "utils.log('log circle100 maxRadius=',maxRadius)"

  L1:
    bespoke:
      namespace: "clock"
      dataRefs:
       - "CT:1-active"
       - "CT:1-reactive"
      formulas:
       - "utils.log('log L1 maxPower=',maxPower)"
       #- "utils.log('log L1 maxRadius=',maxRadius)"
       - "L1re = string(data['CT:1-active'] / maxPower * maxRadius )"
       - "L1im = string(data['CT:1-reactive'] / maxPower * maxRadius )"
       #- "utils.log('log L1=',L1re,L1im)"
      drives:
       - elementName: "line"
         attribsSet:
           x2 : "L1re"
           y2 : "L1im"

```

I get the following error message when trying to obtain maxMessage from the circle:

```
Error occured calculating bespoke formulas for 
<line id="L1" style='stroke-width: 3px; strok…ed"); white-space: pre;' y2="45" x2="100" y1="100" x1="100">
 error = Error: Undefined symbol maxRadius
    onUndefinedSymbol http://localhost:3000/nl/enschede/home/gf/public/plugins/andrewbmchugh-flow-panel/module.js?_cache=1.16.1:2
    _compile http://localhost:3000/nl/enschede/home/gf/public/plugins/andrewbmchugh-flow-panel/module.js?_cache=1.16.1:2
    _compile http://localhost:3000/nl/enschede/home/gf/public/plugins/andrewbmchugh-flow-panel/module.js?_cache=1.16.1:2
    _compile http://localhost:3000/nl/enschede/home/gf/public/plugins/andrewbmchugh-flow-panel/module.js?_cache=1.16.1:2
    _compile http://localhost:3000/nl/enschede/home/gf/public/plugins/andrewbmchugh-flow-panel/module.js?_cache=1.16.1:2
    evaluate http://localhost:3000/nl/enschede/home/gf/public/plugins/andrewbmchugh-flow-panel/module.js?_cache=1.16.1:2
    evaluate http://localhost:3000/nl/enschede/home/gf/public/plugins/andrewbmchugh-flow-panel/module.js?_cache=1.16.1:2
    l http://localhost:3000/nl/enschede/home/gf/public/plugins/andrewbmchugh-flow-panel/module.js?_cache=1.16.1:2
    l http://localhost:3000/nl/enschede/home/gf/public/plugins/andrewbmchugh-flow-panel/module.js?_cache=1.16.1:2
    l http://localhost:3000/nl/enschede/home/gf/public/plugins/andrewbmchugh-flow-panel/module.js?_cache=1.16.1:2
    _M http://localhost:3000/nl/enschede/home/gf/public/plugins/andrewbmchugh-flow-panel/module.js?_cache=1.16.1:2
    fn http://localhost:3000/nl/enschede/home/gf/public/plugins/andrewbmchugh-flow-panel/module.js?_cache=1.16.1:2
    T http://localhost:3000/nl/enschede/home/gf/public/plugins/andrewbmchugh-flow-panel/module.js?_cache=1.16.1:21
    Lf http://localhost:3000/nl/enschede/home/gf/public/build/1247.34022e0fa8ad25da7b32.js:951
    pu http://localhost:3000/nl/enschede/home/gf/public/build/1247.34022e0fa8ad25da7b32.js:953
    ln http://localhost:3000/nl/enschede/home/gf/public/build/1247.34022e0fa8ad25da7b32.js:953
    Zh http://localhost:3000/nl/enschede/home/gf/public/build/1247.34022e0fa8ad25da7b32.js:953
    Nd http://localhost:3000/nl/enschede/home/gf/public/build/1247.34022e0fa8ad25da7b32.js:953
    yh http://localhost:3000/nl/enschede/home/gf/public/build/1247.34022e0fa8ad25da7b32.js:953
    vu http://localhost:3000/nl/enschede/home/gf/public/build/1247.34022e0fa8ad25da7b32.js:953
    Js http://localhost:3000/nl/enschede/home/gf/public/build/1247.34022e0fa8ad25da7b32.js:951
    kd http://localhost:3000/nl/enschede/home/gf/public/build/1247.34022e0fa8ad25da7b32.js:953
module.js:2:769051

```

Kind regards,
Dennis

**Comment by bijwaard** [comment]
Ah, see what went wrong, I have to use the SVG element name "circle" instead of the ID in elementName.

**Comment by bijwaard** [comment]
Here is the first result with maxPower=2000, still have to figure out how to use maxPower from a template variable.

![image](https://github.com/user-attachments/assets/0ac43510-f3a8-4436-a991-54fac7a93076)

I notice that the arrowheads are not placed correctly on the end of the lines, any idea why this fails? They use to line up great with the SVG plugin. It may be because of floats, I'll try to get rid of the decimals.

```
log L1= 89.1587447104481 91.53735857788533
log L2= 181.7314652015254 86.12240998408774
log L3= 68.89826760295432 85.00590009344427

```
