### ISSUE TITLE
Feature Request: Option to Open URLs in the Same Tab

### ISSUE THREAD

**Issue by micaelgg** [andymchugh/andrewbmchugh-flow-panel#68]
It would be great to define if the CELL URL opens in the same tab. Currently it always opens in a new tab.

Thanks for your attention!

**Comment by andymchugh** [comment]
Thanks for the feedback. This has been added and will be in the next build. You can configure it at the site, panel or cell level.
[cell example](https://github.com/andymchugh/andrewbmchugh-flow-panel/blob/main/provisioning/dashboardData/linksSameTabPanelCellSet.yaml#L13)
[panel example](https://github.com/andymchugh/andrewbmchugh-flow-panel/blob/main/provisioning/dashboardData/linksSameTabPanelSet.yaml#L9)
[site example](https://github.com/andymchugh/andrewbmchugh-flow-panel/blob/main/provisioning/dashboardData/linksSameTabSiteSet.yaml#L7)

**Comment by andymchugh** [comment]
published in 1.14.0

**Comment by micaelgg** [comment]
Thank you so much andymchugh
