### ISSUE TITLE
transparent background and diagram size

### ISSUE THREAD

**Issue by bijwaard** [andymchugh/andrewbmchugh-flow-panel#7]
Thanks for this interesting alternative to flowcharting. Just tried to bring my first flowchart diagram to life in a flow panel.

Currently, dark/light theme background seems to be usen as transparent background color. It would be great if color could be selected.

The flow does not occupy the complete panel for some reason, although I chose Fill.
![Screenshot_2024-04-07-00-58-04-00_3aea4af51f236e4932235fdada7d1643](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/6523124/441a8ae9-482d-4631-8e60-e51adbcc025d)

I can add better screenshot and additional remarks when back at my desk.

Kind regards, Dennis

**Comment by andymchugh** [comment]
Thanks for the feedback Dennis. Could you attach your svg to the issue? If it's sensitive, do just delete a bunch of stuff from the middle. I just need the svg that demonstrates the problem so I can see how the viewport and dimensions are defined and have a play around with it.

**Comment by andymchugh** [comment]
I think the scaling problem you are seeing is caused by the width of the panel being less than the width of the svg. i.e. x scaling under 100%. I've just made a fix for that but if you can attach your svg I can check it scales properly with the fix. 

Re the background color, from what I understand, your svg content isn't going to change much when switching grafana from light to a dark theme, so I'd have thought fixing a background color in the svg would make it usable regardless of the theme a user might have setup. Can you explain a bit more why setting the background color in the panel rather than the svg is the more useful solution for you?

**Comment by bijwaard** [comment]
Hi Andy,

Here is a simplified version of the SVG that has the same problem sizing problem, it appears in-line in this message but can be saved as SVG.
![lv-sensors-dashboard](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/6523124/9d94b057-401b-46b0-92a2-d8bf35f63fee)

Regarding the background color there are a number of reasons to keep it transparent in draw.io:

- It would allow to choose a different color when using it in a different dashboards
- When SVG size does not exactly fit the size of the panel, the rest of the panel would get the assigned background color instead of the default panel background
- Figures in documents work better without assigned background color.

Kind regards,
Dennis

**Comment by andymchugh** [comment]
Thanks. the scaling fix does work with your svg so that's good news. The review process with Grafana takes anywhere from 2 days to 3 weeks so I'll hold off submitting for a little bit to bundle other stuff in.

Still thinking about the background color. The panel is aware of whether dark or light them is selected. Is it true to say two values are wanted. i.e. a lightTheme bg color and a darkTheme bg color and then the panel would apply the appropriate one based on selected theme?

**Comment by bijwaard** [comment]
Thanks for looking into this. I don't mind testing a beta version of the plugin to check the new features.

Regarding the background color, I would really like to be able to use a custom color for the whole panel background. This would solve:
- keeping the consistent background color when reshaping the panel
- keeping consistent background color with SVG size is different from panel size.
- make dashboards come to live with other colors besides black and white from the standard themes;-)

**Comment by andymchugh** [comment]
ok, I'll add dark & light theme background color fields to the panel yaml. I think that then meets your need. Say if there's some reason it has to be independent of the yaml and actually drivable as a panel option.

**Comment by bijwaard** [comment]
Being able to set the SVG background color in yaml would be great!
 In my case it does not need to be dark/light theme dependent, for other users it might.

**Comment by andymchugh** [comment]
Background color now drivable via the yaml as of 1.6.0. https://grafana.com/grafana/plugins/andrewbmchugh-flow-panel/

**Comment by bijwaard** [comment]
I found the background setting, and it appears to work set the SVG background color but not the panel backgound itself. The scaling does not seem to work yet for my SVG, and that clearly shows that the background is confined to the SVG part of the panel.

```
# Version 1.6.0 onwards: When undefined the background color is not driven. When defined the color for
# the current theme is used. Colors can be entered in all the normal ways of name, hex, hsl, etc.
background:
  darkThemeColor: "yellow"
  lightThemeColor: "green"
```
Settings "Actual size" and "Fill all" no look almost the same:
![image](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/6523124/f0b12262-5e5c-4421-9b78-303e5ba64d0d)
![image](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/6523124/7bb65cd0-d5a0-4b55-b296-e183b338510c)

**Comment by bijwaard** [comment]
I did a simple experiment to re-shape the dashboard panel and see the panel space at the top grow when reducing size vertically and see the SVG background grow when reducing size horizontally.

Vertically:

![image](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/6523124/c035174d-1307-4506-ad09-99fafd0dc89c)
![image](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/6523124/3e884730-c19e-4ceb-a49e-f4fc982cc188)

 and horizontally:
 
![image](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/6523124/6a7e1403-0cbd-4adb-aeea-0793ef2f7b83)

**Comment by bijwaard** [comment]
When scaling further vertically, the SVG gets even outside the panel

![image](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/6523124/e8ab0309-e7a7-449e-b0ba-c3e9ff53d41a)

**Comment by bitlewis** [comment]
I am having the same exact problem with a larger SVG. When exporting from draw.io, regardless it exports to over 5500 pixels wide. To have the width adjusted to my browser I need to grow the panel so big that the spacing above my image goes to over 850px

![image](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/6572077/7c2e519a-fec6-4754-b892-e06d6156d5dc)

**Comment by andymchugh** [comment]
Re the background color, I misunderstood you. I thought this was an svg background-color request. I've just had a play and changing the background of the area available to the svg does look nicer and is straight-forward, so I'll change it to that. The background of the Highlighter and the timeSlider will be unaffected and will stay at the selected theme.

Re the scaling, I've revisited it and I think with the next tweak the behaviour is correct. I'll push another version in a few days.

**Comment by andymchugh** [comment]
In version 1.7.0 the background color terms now apply to the whole of the panel available to the svg. The only part still excluded is that reserved by the timeSlider and highlighter legend.

This version also fixes scaling. It's just better all round in this respect and whilst maintaining aspect ratio uses all the panel space available.

**Comment by bijwaard** [comment]
Great Andry,

Scaling and background seem to be working fine now, with and without slider, with and without menu highlight menu, and also when re-sizing the panel!
![image](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/6523124/a632dac5-fb9b-4f28-982a-36dfd7a9660e)
![image](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/6523124/c1f87416-fc73-4a18-aa8e-83013ee03b86)

Kind regards,
Dennis

**Comment by andymchugh** [comment]
Great, thanks for confirming.
