### ISSUE TITLE
Time-shifted panel still shows current dates

### ISSUE THREAD

**Issue by psheehymn** [andymchugh/andrewbmchugh-flow-panel#77]
We are experimenting with the Flow plugin and have two panels, one of which shows data for the current date/time, the other showing one week earlier (via the Query options Timeshift field). We would expect that the time bar at the panel bottom would be adjusted to show the period represented by the panel data, but both remain set to the selected time range: 

![FlowComparison](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/93273674/685b6812-d4c9-4a60-986d-0c6aa6680483)

Are we overlooking a setting or option to have the time bar on the time-shifted panel display the correct time range?

**Comment by andymchugh** [comment]
thanks, this sounds like a bug on my part. will have a look...

**Comment by andymchugh** [comment]
this is now fixed on main and will be in the next build

**Comment by andymchugh** [comment]
This has now been published in version 1.16.1. Just reopen if you still have problems.
