### ISSUE TITLE
Enhancement: Allow single total values

### ISSUE THREAD

**Issue by psheehymn** [andymchugh/andrewbmchugh-flow-panel#79]
We use a Real-User Monitoring (RUM) application to gather data about end-user experience on our web portals. We're using the Flow plugin to design flowcharts which illustrate various user journeys within the portal (**main-dashboard -> claims-list -> view-a-claim-> pay-a-claim**, etc.).

The Grafana plugin for the RUM tool can return either a time-series or a single value for the specified time range (the latter being a total count or an average of a time-value, depending on the metric being queried). However, when we flip the queries from time-series to single value, the values on the Flow diagram disappear.

Because our dashboards are designed for executive-level consumption, the single value (as opposed to the time-series) would actually be _very_ useful to us. An executive could get a snapshot of the total flow of traffic for a time period (such as "yesterday") as opposed to the incremental view currently presented.

We request the capability to switch between time-series and single value for the flowchart, either thru a manual option (and please allow the option field to accept a variable to allow this to be changed dynamically) or automatically (such as if one or more of the queries returns only a single value, then the flow-chart flips to single value mode). Obviously, the time slider would be disabled or hidden in single-value mode.

Is there any reason this would not be feasible?

**Comment by andymchugh** [comment]
Can you press on 'Debugging Data' and show me what the raw data and enriched data look like? I need to know what the plugin is receiving to know how to interpret it after it's passed through the toDataFrame conversion.

**Comment by psheehymn** [comment]
Do you want both the time-series and the single value, or just the latter?

**Comment by andymchugh** [comment]
I need to see the data being given to the panel that isn't working for you.

**Comment by psheehymn** [comment]
Here's the log file:
[m4-stage.optum.com-1718915903164.log](https://github.com/user-attachments/files/15919950/m4-stage.optum.com-1718915903164.log)

**Comment by psheehymn** [comment]
Here's the debug data:
[m4-stage.optum.com-1718917550277.log](https://github.com/user-attachments/files/15920131/m4-stage.optum.com-1718917550277.log)

**Comment by andymchugh** [comment]
It's not really readable unfortunately. What I'm after is  a minimal view of the data you want to display. It will be filtered from the -debug-data-enriched' because there's no time but will be present in the 'debug-data-raw' and in the output of grafana's query inspector. If you could show me what that data looks like for a single term I may be able to do something. But without that or instructions on how to generate such data I can't get further.

**Comment by psheehymn** [comment]
Here's an example CSV extracted from the Query Inspector in the panel of the Total version of the query.
[E&I Claims 01 - My Claims - Pay Now-data-2024-06-21 15_02_11.csv](https://github.com/user-attachments/files/15932937/E.I.Claims.01.-.My.Claims.-.Pay.Now-data-2024-06-21.15_02_11.csv)

For comparison, here is the exact same query, switched to return a time-series:
[E&I Claims 01 - My Claims - Pay Now-data-2024-06-21 15_05_11.csv](https://github.com/user-attachments/files/15932962/E.I.Claims.01.-.My.Claims.-.Pay.Now-data-2024-06-21.15_05_11.csv)

**Comment by andymchugh** [comment]
I need to understand the javascript object layout for the above. So I need a minimal example with one data term as shown in the query inspector and the 'debugging data raw'. But it has to be in the javascript object form. That's my input; the csv form doesn't tell me anything.

**Comment by andymchugh** [comment]
Reduce your panel down to just 1 data query returning just one value. Then expand out debugging data raw in the console so I can see how the structure if the incoming data. Also a screenshot of the grafana query inspector result will also help a great deal. Basically I need a readable starting point and it stops becoming readable if there's more than one query in it as its too much information.

**Comment by psheehymn** [comment]
I pared the panel down to a single query. I have included both TimeSeries results and Total (single number) results, as well as screen shots from the Query Inspector. Hopefully these can help.
[m4-stage.optum.com-TimeSeries.log](https://github.com/user-attachments/files/16016218/m4-stage.optum.com-TimeSeries.log)
[m4-stage.optum.com-Total.log](https://github.com/user-attachments/files/16016221/m4-stage.optum.com-Total.log)
![QI-Query-TimeSeries](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/93273674/6d75b008-a8ad-4a97-b2e3-ce12767fd476)
![QI-Data-TimeSeries](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/93273674/1d745ff2-a874-4eb8-a49e-9568a375c97e)
![QI-Query-Total](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/93273674/2651bb0b-3f8a-4db9-b91b-2ca631738741)
![QI-Data-Total](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/93273674/3ff85b3c-b554-47d0-8058-3909fd958d0a)

**Comment by andymchugh** [comment]
Thanks for trying. Unfortunately it's still not really helping. The log isn't showing anything useful and the query screenshots don't show the response. It's the query response that is the input to the panel. A screenshot like this showing the query response would help:

![image](https://github.com/andymchugh/andrewbmchugh-flow-panel/assets/144024509/a1228cd0-762f-4b6e-878d-11a071789d12)

**Comment by psheehymn** [comment]
Here is the Query JSON for both the TimeSeries and Total versions (they were too long to screenshot, so I expanded them and used the **Copy to Clipboard** option).
[QI-Query-TimeSeries.txt](https://github.com/user-attachments/files/16021935/QI-Query-TimeSeries.txt)
[QI-Data-Total.txt](https://github.com/user-attachments/files/16021936/QI-Data-Total.txt)

**Comment by andymchugh** [comment]
That's perfect. Thanks for persevering with it. I know what to do now

**Comment by psheehymn** [comment]
Awesome! Thanks Andy!
