### ISSUE TITLE
Possible to hide the bottom bar / pause button?

### ISSUE THREAD

**Issue by yo8192** [andymchugh/andrewbmchugh-flow-panel#90]
Now that you added all the features I needed (thanks!), I'm ready to switch from FlowCharting to Flow Panel.

One thing I noticed is that Flow Panel displays a fixed-height bar at the bottom of the panel, with the pause button (and the time slide bar if I enabled it).
The problem is that it takes a lot of screen space when the panel is small, e.g. to display on a mobile phone.

Example, with FlowCharting on the left, and Flow Panel on the right:
![image](https://github.com/user-attachments/assets/693af245-63c4-4919-9a2e-76021f9ff284)

Is there a way to hide the pause button / that bottom bar and reclaim the screen space to display the flow diagram bigger?

**Comment by andymchugh** [comment]
There isn't currently. I figured given animations can be triggering there should always be a way to pause them on screen. But I guess I should offer the choice. I can add an option for it.

**Comment by andymchugh** [comment]
this has been built into 1.16.2. Will close out when published.

**Comment by andymchugh** [comment]
1.16.3 has been published. Hiding this is now possible via the grafana panel options.

**Comment by yo8192** [comment]
That works nicely, Thanks for the super quick turn-around!
I've now fully migrated to the Flow Panel :+1:
