### ISSUE TITLE
arrowHead of line is not correctly placed when x2 and y2 attributes are driven by measurements

### ISSUE THREAD

**Issue by bijwaard** [andymchugh/andrewbmchugh-flow-panel#97]
When attributes are driven by measurements, the arrowhead is not correctly driven from measurements. When comparing original SVG and modified SVG, I noticed that the defined markers miss the attributes refX="1.5" refY="1.5".
The refX and refY define the point of attachment of the [marker](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/marker) to the line.

![image](https://github.com/user-attachments/assets/0ac43510-f3a8-4436-a991-54fac7a93076)

Here is the relevant part of the original SVG:

```
    <defs>
      <marker id="markerArrowRed" markerWidth="3" markerHeight="3" refX="1.5" refY="1.5" orient="auto">
          <path d="M1,0 L1,3 L2,1.5 L1,0" style="fill: red" />
      </marker>
    </defs>
     <g>
      <line x1="100" y1="100" x2="100" y2="45" style="stroke-width: 3px; stroke: red; marker-end: url(#markerArrowRed);"       id="L1" />
     </g>
```     
This is the SVG after modification (obtained through firefox inspect):

```
    <defs>
      <marker orient="auto" id="markerArrowRed">
          <path style="fill: red" d="M1,0 L1,3 L2,1.5 L1,0"></path>
      </marker>
     <g>
      <line id="L1" style="stroke-width: 3px; stroke: red; marker-end: url(&quot;#markerArrowRed&quot;); white-space: pre;" y2="86.40646423489822" x2="105.41752351150924" y1="100" x1="100"></line>
     </g>
```
I can reproduce the wrong placement of the arrowhead with SVG editor inkscape.

_Originally posted by @bijwaard in https://github.com/andymchugh/andrewbmchugh-flow-panel/issues/67#issuecomment-2288098041_

**Comment by bijwaard** [comment]
As a work-around, I tried to drive marker refX and refY from formula, but this is not allowed, probably because they are in the SVG definition section.

```
  markerArrowRed:
    bespoke:
      formulas:
      - "ref = 1.5"
      drives:
      - elementName: "marker"
        attribsSet:
          refX: "ref"
          refY: "ref"
```

attribute drive [ refX ] not allowed on element 
<marker id="markerArrowRed" orient="auto">
module.js:2:766239

attribute drive [ refY ] not allowed on element 
<marker id="markerArrowRed" orient="auto">
module.js:2:766239

**Comment by bijwaard** [comment]
Thanks for the workaround! lowcase attributes work fine
I also implemented autoscaling in steps of 500 inspired by your formula.
![image](https://github.com/user-attachments/assets/72ecfe33-cb96-48e1-a60b-f5955691cbd5)

**Comment by andymchugh** [comment]
All the camelCase marker element attributes now work in 1.16.4, just published.
